### PR TITLE
Fixing structure typo

### PR DESCRIPTION
**Pull request by vsukhin**

### CODE REVIEW

**Comment by vsukhin** [comment]
Typo fixing

**Comment by vsukhin** [comment]
Please pay attention.
1. No public method interface was changed.
2. One public method internals were updated.
3. Two public methods were added.
4. One internal structure was maden public in order to be transferred between BeforeRequest and AfterRequest (meaning, it couldn't be used before by clients)

If you don't have principal objections, I can spend more time on unit testing

**Comment by vsukhin** [comment]
Reverting typo pr

**Comment by eyberg** [comment]
LGTM

**Pull request merged**
